modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
issueTrackerURL="https://github.com/FinnSetchell/MoogsEndStructures/issues" #optional
license="GNU Lesser General Public License v3.0"

[[mods]] #mandatory
modId="mes" #mandatory
logoFile= "assets/mes/icon.png"
logoBlur=false
version="${version}" #mandatory
displayName="Moog's End Structures" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/moogs-end-structures"
authors="FinnDog"
credits="Thanks to everyone who has contributed buildings for this mod, as well as TelepathicGrunt for their structure mod template and rs!"
description = '''lots of structures made with vanilla blocks and entities bringing life to your world!
Discover loot, enemies, & villagers along the way!

Join our community here: https://discord.gg/S5nffJbuvA
''' #mandatory (Supports multiline text)

[[mixins]]
    config = "mes-neoforge.mixins.json"

[[mixins]]
    config = "mes-common.mixins.json"

[[dependencies.mvs]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,)"