modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/FinnSetchell/MoogsNetherStructures/issues" #optional
license="https://github.com/FinnSetchell/MoogsNetherStructures/blob/1.20/LICENSE"

[[mods]]
    modId="mns"
    logoFile= "assets/mns/icon.png"
    logoBlur=false
    version="${version}"
    displayName="Moog's Nether Structures"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/moogs-nether-structures"
    authors="FinnDog"
    credits="Thanks to all of the amazing builders as well as TelepathicGrunt for their structure mod template and rs"
    description='''
    Moogs Nether Structures brings life, fun and variety to your Minecraft world!
    Explore awesome new structures made with vanilla blocks and entities, and discover loot,
    enemies, and more along the way. This mod is compatible with any modpack and keeps
    the vanilla feel of the game!
    '''

[[mixins]]
    config = "mns-neoforge.mixins.json"

[[mixins]]
    config = "mns-common.mixins.json"

[[dependencies.mns]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.5,)"